### ISSUE TITLE
Arrays containing Pairs seems to not work

### ISSUE THREAD

**Issue by Ofenhed** [JustusAdam/mustache#23]
scripts.mustache:
```
{{#inlineJavascripts}}
<script>{{javascript}}</script>
{{/inlineJavascripts}}
```

Renderer.hs
```
    object [ "inlineJavascripts" ~> map (\x -> "javascript" ~> x) (["alert('Hello world');", "document.write('Gone!');"] :: [Text.Text]) ]
```

Result:
```
<script></script>
<script></script>
```

Own experiment is GHCI:
```
*> "name" ~> ("Alice" :: Text)
("name","Alice")
*> "people" ~> ["name" ~> ("Alice" :: Text), "name" ~> ("Bob" :: Text)]
("people",[["name","Alice"],["name","Bob"]])
*> toMustache $ "name" ~> ("Alice" :: Text)
["name","Alice"]
```

**Comment by JustusAdam** [comment]
Okay, I have tested it myself and it is working as intended.

Here's the issue with your code: If you want to use a named lookup like `{{javascript}}` the target you call this on must be an object.
What you constructed in the first instance was an object with a key `inlineJavascripts` and the value at this key was `Array (Array Text)`, aka `[["javascript", "alert('Hello world');"], ["javascript", "document.write('Gone!');"]`. So your current scope in the section is not an object, but rather an array with two values, because that is how tuples are serialised.

If you want to do named lookup, you will want to use an object as scope in the section, like so:]

```Haskell
object [ "inlineJavascripts" ~> map (\x -> object ["javascript" ~> x]) (["alert('Hello world');", "document.write('Gone!');"] :: [Text]) ]
```

alternatively, if you really only have one value in that scope, you can iterate directly over the array, by using an implicit tag `{{.}}`. This tag simply prints whatever value is the current scope.

```Haskell
template = "{{#inlineJavascripts}}\n<script>{{.}}</script>\n{{/inlineJavascripts}}\n"
vals = object [ "inlineJavascripts" ~> (["alert('Hello world');", "document.write('Gone!');"] :: [Text]) ]
```

**Comment by Ofenhed** [comment]
Ok, thank you, that worked. I looked for an implicit tag without finding it, that seems to be the better option for me.

**Comment by JustusAdam** [comment]
Yeah, they buried those pretty deep in the spec. I also only found it when I ran the library against their test cases.  :D
